version: '3'
services:
    
    server1:
      image: salmaankhan/web-service:v1
      ports:
        - "8080:3001"
      depends_on:
        - "db1"
      links:
        - "db1"
      environment:
        - DATABASE_IP=192.168.99.100
    db1:
      container_name: db1
      image: salmaankhan028/database-service:v1
      ports:
      - "3306:3306"
      environment:
      - user=root
      - pass=123
